# This is a basic workflow to help you get started with Actions

name: Steve Meadows Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on:  ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "First output"
          echo "Second output" 
          echo "Hello Steven Meadows"
      - name: Print Goodbye
        run: echo "Goodbye Steven Meadows"
